# Generated by Django 5.0.6 on 2024-09-26 16:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icd10',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'icd10',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('ssn', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('employee_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('vitals_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulse', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('respiratory_rate', models.IntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surgeries', models.TextField()),
                ('allergies', models.TextField()),
                ('medical_conditions', models.TextField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kame_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress_notes', models.TextField()),
                ('lab_data', models.TextField()),
                ('imaging_reports', models.TextField()),
                ('medications', models.TextField()),
                ('inmunizations', models.TextField()),
                ('Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kame_app.icd10')),
                ('history_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kame_app.medicalhistory')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kame_app.patient')),
                ('vitals_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kame_app.vitalsigns')),
            ],
        ),
    ]
