# Generated by Django 5.1 on 2024-10-01 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kame_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='Code',
            new_name='code',
        ),
    ]
