# Generated by Django 4.2 on 2024-10-07 18:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("kame_app", "0002_customuser_is_active_customuser_is_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitalsigns",
            name="patient_id",
            field=models.ForeignKey(
                default=uuid.uuid4,
                on_delete=django.db.models.deletion.CASCADE,
                to="kame_app.patient",
            ),
        ),
    ]
