# Generated by Django 5.1 on 2024-10-07 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kame_app', '0002_customuser_is_active_customuser_is_staff_and_more'),
        ('kame_app', '0002_rename_code_medicalrecord_code'),
    ]

    operations = [
    ]
