# Generated by Django 4.2 on 2024-10-07 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kame_app", "0004_alter_medicalrecord_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medicalrecord",
            old_name="Code",
            new_name="code",
        ),
    ]
