# Generated by Django 5.1 on 2024-10-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kame_app', '0005_rename_code_medicalrecord_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_visited',
            field=models.DateField(blank=True, null=True),
        ),
    ]
