# Generated by Django 5.1 on 2024-10-14 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kame_app', '0006_patient_last_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsigns',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kame_app.patient'),
        ),
    ]
