# Generated by Django 5.0.6 on 2024-10-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kame_app', '0007_alter_vitalsigns_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='last_visited',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
